language: node_js
cache: yarn
node_js:
  - '10'
  - '11'
  - '12'
install:
  - yarn
script:
  - yarn lint
  - yarn test
after_script: 'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'
