name: build

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: ['10', '12']

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
