name: build

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['10', '12', '14']

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
